dist: trusty
sudo: false
language: generic

git:
  depth: 10

branches:
  only:
    - master

cache:
  directories:
    - $HOME/downloads

install:
  - ./setup-travis.sh

before_script:
  - /tmp/emacs/bin/emacs --batch -q -Q -l init.el

# Build the website
script:
  - ./deploy.sh
