#+HUGO_BASE_DIR: ../
#+SEQ_TODO: TODO DRAFT DONE
#+COLUMNS: %TODO %42ITEM %TAGS

* Pages
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:END:

** The T. Temple Tuttle Memorial Music Competition
:PROPERTIES:
:EXPORT_FILE_NAME: music-competition
:END:

- Date: *March 30, 2018*
- Venue: *Music Building, Cleveland State University, OH, United States.*
- Last Date for registration: *March 11, 2018*
- The entry fee: US $75 per category

[[/][Register Here]]

*** FAQs

**** I am the defending champion. Am I allowed to ...?

Yes! Yes! Roger Federer has 8 Wimbledon titles to his credit. What's
your count?

**** Okay. But may I compete in the next higher age category?

Age is just a number. How about one of our advanced-level categories.

**** What time is my category scheduled for on Friday?

The fight for Grand slam happens in several courts at once. Watch this
space for the schedule, showing the order of events in each room at the
Music Building of Cleveland State University.

**** Do I need to bring a Sruti box?
Yes. Unless you can tune a tambura by singing Sa, Pa, Sa at will.\\

**** Do you provide musical instruments? Can I borrow someone else's instrument?

We do not provide instruments. As a champion, do you really want to?

**** Is there a penalty for going over time? Should I prepare a piece that fits within the time, or just perform the best item I can and be cut off at the time-limit?

Not really. But, isn't the championship all about getting the time ---
and the timing right? Unless it is an epic final at the centre court.
Roger that? :)

**** For the niraval / kalpana swaram category, do I need to perform the entire kriti?

Nope. It is just the rally that we'd love to watch. Over and over.

**** In the kriti competition, the rules say that no kalpana swaram may be performed. Are chittaswarams allowed?

Only if the composer convinced the composition along with the chittaswaram.

**** Can I change my entry after I have registered?

You can do so on the registration page (by clicking on *Edit this entry*) before the deadline.

**** How long should I plan to stay in Cleveland for the competition?

The competition is on Friday. The prize ceremony is on the Sunday afternoon ---
the Ester day.

The grand finale is always on the centre court.

Get your tickets /here/

** Pancharatnam
:PROPERTIES:
:EXPORT_FILE_NAME: pancharatnam
:END:

** Srinivasa Kalyanam
:PROPERTIES:
:EXPORT_FILE_NAME: srinivasa-kalyanam
:END:

** Season Pass
:PROPERTIES:
:EXPORT_FILE_NAME: season-pass
:END:

*All Season Family Pass: 116 USD*

*All Season Couple Pass: 108 USD*

*All Season Individual Pass: 51 USD*

** Artists
:PROPERTIES:
:EXPORT_FILE_NAME: artists
:END:

** Home Coming
:PROPERTIES:
:EXPORT_FILE_NAME: home-coming
:END:

** Partnerships
:PROPERTIES:
:EXPORT_FILE_NAME: partnerships
:END:

** Committee
:PROPERTIES:
:EXPORT_FILE_NAME: committee
:END:

- R. Balasubramaniam

- V.V. Sundaram

- Gomathy Balasubramaniam

- K. Venkataraman

- Roger Natarajan

- Jaya Natarajan

- Sunitha

- Ashok Grandhee

- Radhika Balasubramaniam

- Gopi Sundaram
* COMMENT Local Variables
# Local Variables:
# org-hugo-allow-export-after-save: t
# org-export-with-author: nil
# End:
